### ISSUE TITLE
KIT-0003: Query Parameters for Codable Routing

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/evolution#7]

**Comment by hactar** [comment]
Haha, excellent, I was looking at the new codable routes thing when I noticed that I can't use it im my scenario because of KIT-0002, and how I wished this was type safe too. This would be an excellent addition.

**Comment by seabaylea** [comment]
FYI, the PR for this is being worked on here:
https://github.com/IBM-Swift/Kitura/pull/1190

**Comment by ianpartridge** [comment]
This was released in Kitura 2.2

**Comment by hactar** [comment]
So I've come back to see if I can use the new changes, but Kitura's Codable query parameters is still very REST focused.

```
router.get(<#T##route: String##String#>, handler: <#T##(QueryParams, @escaping ([Decodable & Encodable]?, RequestError?) -> Void) -> Void#>)
```

Cool, but there's no way to just return a `Codable`, it has to be an array of `Codable`. It would be more flexible if we had a way of setting up a get route with a `QueryParams`, but just being able to return a `Codable` instead of an array of `Codable` as one is currently forced to do.

**Comment by seabaylea** [comment]
Hi @hactar. Would it be possible for you to provide some information on what your scenario is? That would help to make sure that it gets covered.

**Comment by hactar** [comment]
Ok, so lets say I'm writing an API with calls such as this:

`curl "https://some.server/message?q=wie%20komme%20ich%20zum%20rathaus&resolvewave=true&client=android"`

So, I'd like to be able to create a `QueryParams` with all expected types and kitura to do the type checking for me, returning bad request 400 if `q` is missing for example.

```
public struct ServerRequest: Codable {
    
    public let q: String
    public let client: String?
    public let resolvewave: Bool?
    
}
```

So far so good, the new codable routing can do this already. But for this GET request, I want to return a `Codable`, not a `Codable` array:

```
{
  "_text": "wie komme ich zum rathaus",
  "msg_id": "0Y143VzFbITh8ZTuL",
  "additionalQuickReplies": [
    {
      "messageToShow": "Rathaus"
    }
  ]
}
```

There appears to be no way to to this with the current methods as what I'm trying to return is not an Array of JSON, but just JSON.  With Kituras current methods I have to return a `[Decodable & Encodable]?` -> I have to return an array of `Codable` or nil, but not just a `Codable`.

I need:

```
public func get<Q: QueryParams, O: Codable>(_ route: String, handler: @escaping (Q, @escaping CodableResultClosure<O>) -> Void) 
```

But we only have: 
... Codable**Array**ResultClosure<O>) -> Void) 
Hope that clears up what I mean.

**Comment by seabaylea** [comment]
Hi @hactar. Just to let you know, this is actively being looked at by @ddunn2

**Comment by hactar** [comment]
I've been playing around more with Codable routing, and its great, but the current implementation should be renamed to Codable REST Routing, because assumptions are being made about parameters and return values that work great for REST, but cumbersome for non REST apis. The issue described is one of the issues, another one I just noticed is that when you use the post Codable route, the return code is `HTTP/1.1 201 Created`, which makes complete sense for a REST api, but does not make sense for for other types of api, where nothing might be being created in a post server-side, and a 200 code would make more sense.

I'd propose creating a generic Codable Routing System instead which does not make assumptions  about that the developer is trying to make a REST api (assumptions such as: get returns arrays, post creates objects, etc). Get and post take Codable and return Codable or nil. 200 is returned if all went well. 400 (or similar) is returned when one has problem decoding the Query Parameters or the posted Codable. 500 is returned on other errors. etc.

Then, the current Codable REST Routing could be a subclass of this more generic system where these assumptions are correct and help instead of hinder the developer. This subclass would then work as it does currently.

Other subclasses could also be created for other types of standardized api.
